name: Deploy on main server

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull repo
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ./pull.sh 
        host: end2end.network
        username: github-webhook
        privateKey: ${{secrets.PRIVATE_KEY}}
